# -*- coding: utf-8 -*-
"""Criando_um_Rest_Service.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G89h_FBMpWtnNnPu0Fyrmt1WioRz5IiR
"""

# Instalando

!pip install flask flask-ngrok

# Criando o server
import json


from flask_ngrok import run_with_ngrok
from flask import Flask, request, make_response


app = Flask(__name__)

run_with_ngrok(app)   #starts ngrok when the app is run
@app.route("/", methods = ['GET', 'POST', 'DELETE'])
def home():

    pessoas = [{"nome": "Rodrigo Aglinskas"},
               {"nome": "Rodrigo da"},
               {"nome": "Rodrigo Costa"},
               {"nome": "Rodrigo DaCostaAglinskas"}]
    response = make_response(json.dumps(pessoas))
    response.content_type = "application/json"

    return response

    #return "<h1>Running Flask on Google Colab!</h1>"
  
app.run()